# .github/workflows/image-optimizer.yml
name: Image Optimizer
on:
  push:
    paths:
      - 'image/**'  # This will trigger when files are added to the images folder

jobs:
  optimize:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Pillow
          
      - name: Create optimizer script
        run: |
          cat > optimize.py << 'EOL'
          import os
          from PIL import Image
          
          def optimize_image(input_path, output_path):
              try:
                  with Image.open(input_path) as img:
                      # Convert RGBA to RGB if necessary
                      if img.mode in ('RGBA', 'LA'):
                          background = Image.new('RGB', img.size, 'white')
                          background.paste(img, mask=img.split()[-1])
                          img = background
                      
                      # Max dimensions
                      max_size = (800, 800)
                      if img.size[0] > max_size[0] or img.size[1] > max_size[1]:
                          img.thumbnail(max_size, Image.Resampling.LANCZOS)
                      
                      # Save optimized image
                      img.save(
                          output_path,
                          quality=85,
                          optimize=True,
                          progressive=True
                      )
                      print(f"Optimized: {input_path}")
              except Exception as e:
                  print(f"Error processing {input_path}: {str(e)}")
          
          def process_directory(input_dir, output_dir):
              os.makedirs(output_dir, exist_ok=True)
              
              for root, _, files in os.walk(input_dir):
                  for filename in files:
                      if filename.lower().endswith(('.png', '.jpg', '.jpeg', '.webp')):
                          rel_path = os.path.relpath(root, input_dir)
                          input_path = os.path.join(root, filename)
                          output_subdir = os.path.join(output_dir, rel_path)
                          os.makedirs(output_subdir, exist_ok=True)
                          output_path = os.path.join(output_subdir, filename)
                          optimize_image(input_path, output_path)
          
          if __name__ == "__main__":
              process_directory('images', 'images_optimized')
          EOL
          
      - name: Run optimizer
        run: python optimize.py
        
      - name: Commit optimized images
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add images_optimized/
          git commit -m "Optimize images" || echo "No changes to commit"
          git push
