name: Image Optimizer

on:
  push:
    paths:
      - 'image/**'  # Trigger on changes to images folder
    branches:
      - main        # or your default branch

jobs:
  optimize:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Pillow
          
      - name: Run image optimizer
        run: python .github/scripts/main.py
        
      - name: Commit optimized images
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add image_optimize/
          git commit -m "Optimize images" || echo "No changes to commit"
          git push
